# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Overrides greetd's config.toml with the noctalia-greeter default, if greetd
# was enabled as the display manager.
dontChroot: false
timeout: 60
script:
 - command: |
      if pacman -Qs noctalia-greeter >/dev/null 2>&1; then
        echo "noctalia-greeter was selected. Overriding /etc/greetd/config.toml..."
        cp -f /usr/share/noctalia-greeter/greetd/config.toml /etc/greetd/config.toml
        usermod -d /var/lib/noctalia-greeter -s /usr/bin/nologin greeter
        chown -R root: /etc/greetd
        chmod 644 /etc/greetd/config.toml
      fi

i18n:
  name: "Configuring noctalia-greeter..."
