# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
---

dontChroot: false

script:
 - "/etc/calamares/scripts/ucode-setup"
 - "-rm /etc/calamares/scripts/ucode-setup"

i18n:
 name: "Installing CPU microcode"
