# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Overrides greetd's config.toml with the noctalia-greeter default, if greetd
# was enabled as the display manager.
dontChroot: false
timeout: 60
script:
 - command: |
      if systemctl is-enabled greetd.service >/dev/null 2>&1; then
        echo "greetd was selected. Overriding /etc/greetd/config.toml..."
        cp -f /usr/share/noctalia-greeter/greetd/config.toml /etc/greetd/config.toml
        chown -R root: /etc/greetd
        chmod 644 /etc/greetd/config.toml
      else
        echo "greetd was not selected. Skipping configuration."
      fi

i18n:
  name: "Configuring display manager..."
