name: issues

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "remove in-progress label"
        if: github.event.issue.state != 'open'
        run: |
          curl -X DELETE \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/hacking%3A%20in-progress"

